language: android
jdk: oraclejdk7
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.3

    # The SDK version used to compile your project
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-23

env:
  global:
    # set a larger time out (default = 2 min.)
    - ADB_INSTALL_TIMEOUT=10

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

sudo: false

script: ./gradlew connectedAndroidTest
